[deployment]
# High-traffic deployment configuration for 1-10 lakh users
autoscaleConfig = { min = 2, max = 20 }  # Scale from 2 to 20 instances
cpuLimit = 2.0  # 2 CPU cores per instance
memoryLimit = 4096  # 4GB RAM per instance

[deployment.env]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=3072 --optimize-for-size"

[[ports]]
localPort = 5000
externalPort = 80